/**
 * STTI Profiles Data - Inline Module
 * Generated by sync-profiles.py from STTI Master Profiles.md
 *
 * This file embeds profile data directly in the HTML to avoid CORS issues
 * when opening index.html directly from the file system (file:// protocol).
 *
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten by sync-profiles.py
 */

window.STTI_PROFILES = {
  "IP-Architect": {
    "archetypeDescription": {
      "content": "<strong>Inner Guide</strong> is your dominant sensemaking archetype, and <strong>Producer</strong> is your secondary. This combination creates a converter's approach to sensemaking. You excel at transforming deep insights into practical applications, bridging the gap between meaning and action. Your strength lies in your ability to take abstract understanding and convert it into concrete, productive outcomes."
    },
    "orientationDescription": {
      "content": "As an <strong>IP-Architect</strong>, you have a <strong>Diagonal</strong> profile (notice how the image spans diagonally across quadrants). Your type of diagonal profile is known as a \"converter.\" You excel at transforming inner insights into productive action, bridging the gap between meaning and execution. Your diagonal nature allows you to move fluidly between reflection and execution. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Inner Guide",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself getting lost in an echo chamber of your own ideas. You're reflecting on what matters most to you…but without outside input, your perspective can become narrow.\n\nTo break through, you need to broaden your perspective. Activate your <strong>Synthesizer</strong> to explore diverse ideas and sources. Then, you can activate your <strong>Creative</strong> to express your enriched understanding in new ways.\n\n---\n\n<strong>Your secondary sticking point:</strong> You can get caught taking action based solely on what works best for you, without considering the broader context or audience.\n\nTo break through, you need to identify the needs of your audience. Activate your <strong>Creative</strong> to understand what resonates with others. Then, you can activate your <strong>Synthesizer</strong> to integrate outside perspectives into your action plan."
    }
  },
  "IP-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Inner Guide</strong> is your dominant sensemaking archetype, and <strong>Producer</strong> is your secondary. This combination creates a converter's approach to sensemaking. You excel at transforming deep insights into practical applications, bridging the gap between meaning and action. Your strength lies in your ability to take abstract understanding and convert it into concrete, productive outcomes."
    },
    "orientationDescription": {
      "content": "As an <strong>IP-Gardener</strong>, you have a <strong>Diagonal</strong> profile (notice how the image spans diagonally across quadrants). Your type of diagonal profile is known as a \"converter.\" You excel at transforming inner insights into productive action, bridging the gap between meaning and execution. Your diagonal nature allows you to move fluidly between reflection and execution. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Inner Guide",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself getting lost in an echo chamber of your own ideas. You're reflecting on what matters most to you…but without outside input, your perspective can become narrow.\n\nTo break through, you need to broaden your perspective. Activate your <strong>Synthesizer</strong> to explore diverse ideas and sources. Then, you can activate your <strong>Creative</strong> to express your enriched understanding in new ways.\n\n---\n\n<strong>Your secondary sticking point:</strong> You can get caught taking action based solely on what works best for you, without considering the broader context or audience.\n\nTo break through, you need to identify the needs of your audience. Activate your <strong>Creative</strong> to understand what resonates with others. Then, you can activate your <strong>Synthesizer</strong> to integrate outside perspectives into your action plan."
    }
  },
  "IS-Architect": {
    "archetypeDescription": {
      "content": "<strong>Inner Guide</strong> is your dominant sensemaking archetype, and <strong>Synthesizer</strong> is your secondary. This combination creates a philosophical approach to sensemaking. You naturally seek deep understanding and meaning, often spending significant time in reflection and analysis. Your strength lies in your ability to synthesize complex ideas and find underlying patterns, though you may sometimes struggle with moving from contemplation to action."
    },
    "orientationDescription": {
      "content": "As an <strong>IS-Architect</strong>, you have a <strong>Western</strong> profile (notice how the image is predominantly focused on the western side). Your profile is known as a \"philosopher.\" Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Inner Guide",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself getting lost in your mind. You're reflecting, or analyzing, or trying to understand…but then come the doubts, and you're caught in paralysis by analysis.\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to set a goal or deadline and take some action. Then, you can activate your <strong>Creative</strong> to find innovative ways to manifest your deep insights.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your curious mind can dive so deeply into topics that you find yourself following a trail of 'just one more' source.\n\nTo break through, you need to do something with your knowledge. Activate your <strong>Creative</strong> to express what you've learned. Then, you can activate your <strong>Producer</strong> to create with purpose.\n---\n\n<strong>As an Inner Guide, moving to the Synthesizer:</strong>\n\nWhen you combine your Inner Guide and Synthesizer archetypes with an Architect tendency, it's most difficult to access your Creative archetype—yet that's exactly what you most need. Since your tendency is to architect, the easiest way to move from reflection to expression is by tapping into your Producer archetype, which aligns with your structured approach.\n\n<strong>How can you tie your current activity or problem to a concrete outcome or goal? How can your Producer help pull your work along?</strong>\n\nOnce your Producer is activated, you will likely find it becomes easier to drop into your Creative archetype, allowing you to find unique ways to express your deep insights."
    }
  },
  "IS-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Inner Guide</strong> is your dominant sensemaking archetype, and <strong>Synthesizer</strong> is your secondary. This combination creates a philosophical approach to sensemaking. You naturally seek deep understanding and meaning, often spending significant time in reflection and analysis. Your strength lies in your ability to synthesize complex ideas and find underlying patterns, though you may sometimes struggle with moving from contemplation to action."
    },
    "orientationDescription": {
      "content": "As an <strong>IS-Gardener</strong>, you have a <strong>Western</strong> profile with a tendency to <strong>garden</strong> (notice how the image is predominantly focused on the western side). Western profiles are known as \"philosophers.\" Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Inner Guide",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself getting lost in your mind. You're reflecting, or analyzing, or trying to understand…but then come the doubts, and you're caught in paralysis by analysis.\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to set a goal or deadline and take some action. Then, you can activate your <strong>Creative</strong> to find innovative ways to manifest your deep insights.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your curious mind can dive so deeply into topics that you find yourself following a trail of 'just one more' source.\n\nTo break through, you need to do something with your knowledge. Activate your <strong>Creative</strong> to express what you've learned. Then, you can activate your <strong>Producer</strong> to create with purpose.\n---\n\n<strong>As an Inner Guide, moving to the Synthesizer:</strong>\n\nWhen you combine your Inner Guide and Synthesizer archetypes with a Gardener tendency, it's most difficult to access your Producer archetype—yet that's exactly what you most need. Since your tendency is to garden, the easiest way to move from reflection to expression is by tapping into your Creative archetype, which aligns with your flexible, emergent approach.\n\n<strong>What wants to emerge from your current reflection? How might your Creative archetype express this organically?</strong>\n\nOnce your Creative is activated, you will likely find it becomes easier to move into your Producer archetype, allowing you to find natural ways to manifest your deep insights."
    }
  },
  "IC-Architect": {
    "archetypeDescription": {
      "content": "<strong>Inner Guide</strong> is your dominant sensemaking archetype, and <strong>Creative</strong> is your secondary. This combination creates an explorer's approach to sensemaking. You thrive on creative discovery and meaningful investigation, naturally seeking novel perspectives and innovative solutions. Your strength lies in your ability to venture into uncharted territory and find unique insights that others might miss."
    },
    "orientationDescription": {
      "content": "As an <strong>IC-Architect</strong>, you have a <strong>Southern</strong> profile with a tendency to <strong>architect</strong> (notice how the image is predominantly focused on the southern side). Southern profiles are known as \"explorers.\" They thrive on creative introspection and meaningful discovery, combining inner guidance with creative expression. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Inner Guide",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself with so many ideas, interests and insights that you feel scattered across too many different projects and pursuits.\n\nTo break through, you need to organize your insights. Activate your <strong>Synthesizer</strong> to connect your ideas into coherent patterns. Then, you can activate your <strong>Producer</strong> to systematically manifest your organized vision.\n\n---\n\n<strong>Your secondary sticking point:</strong> You can get lost in perfecting your vision. You're creating, iterating, refining…but as they say: 'Real artists ship.'\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to set deadlines and ship your work. Then, you can activate your <strong>Synthesizer</strong> to make sense of what you've created."
    }
  },
  "IC-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Inner Guide</strong> is your dominant sensemaking archetype, and <strong>Creative</strong> is your secondary. This combination creates an explorer's approach to sensemaking. You thrive on creative discovery and meaningful investigation, naturally seeking novel perspectives and innovative solutions. Your strength lies in your ability to venture into uncharted territory and find unique insights that others might miss."
    },
    "orientationDescription": {
      "content": "As an <strong>IC-Gardener</strong>, you have a <strong>Southern</strong> profile with a tendency to <strong>garden</strong> (notice how the image is predominantly focused on the southern side). Southern profiles are known as \"explorers.\" They thrive on creative introspection and meaningful discovery, combining inner guidance with creative expression. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Inner Guide",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself with so many ideas, interests and insights that you feel scattered across too many different projects and pursuits.\n\nTo break through, you need to organize your insights. Activate your <strong>Synthesizer</strong> to connect your ideas into coherent patterns. Then, you can activate your <strong>Producer</strong> to systematically manifest your organized vision.\n\n---\n\n<strong>Your secondary sticking point:</strong> You can get lost in perfecting your vision. You're creating, iterating, refining…but as they say: 'Real artists ship.'\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to set deadlines and ship your work. Then, you can activate your <strong>Synthesizer</strong> to make sense of what you've created."
    }
  },
  "PI-Architect": {
    "archetypeDescription": {
      "content": "<strong>Producer</strong> is your dominant sensemaking archetype, and <strong>Inner Guide</strong> is your secondary. This combination creates a converter's approach to sensemaking. You excel at transforming deep insights into practical applications, bridging the gap between meaning and action. Your strength lies in your ability to take abstract understanding and convert it into concrete, productive outcomes."
    },
    "orientationDescription": {
      "content": "As a <strong>PI-Architect</strong>, you have a <strong>Diagonal</strong> profile with a tendency to <strong>architect</strong> (notice how the image spans diagonally across quadrants). Your type of diagonal profile is known as a \"converter.\" You excel at transforming inner insights into productive action, bridging meaning with execution. Your diagonal nature allows you to move fluidly between reflection and creation. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Producer",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself taking action based solely on what works best for you, without considering the broader context or audience.\n\nTo break through, you need to identify the needs of your audience. Activate your <strong>Creative</strong> to understand what resonates with others. Then, you can activate your <strong>Synthesizer</strong> to integrate outside perspectives into your action plan.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your reflective side can get lost in an echo chamber of your own ideas. You're reflecting on what matters most to you…but without outside input, your perspective can become narrow.\n\nTo break through, you need to broaden your perspective. Activate your <strong>Synthesizer</strong> to explore diverse ideas and sources. Then, you can activate your <strong>Creative</strong> to express your enriched understanding in new ways."
    }
  },
  "PI-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Producer</strong> is your dominant sensemaking archetype, and <strong>Inner Guide</strong> is your secondary. This combination creates a converter's approach to sensemaking. You excel at transforming deep insights into practical applications, bridging the gap between meaning and action. Your strength lies in your ability to take abstract understanding and convert it into concrete, productive outcomes."
    },
    "orientationDescription": {
      "content": "As a <strong>PI-Gardener</strong>, you have a <strong>Diagonal</strong> profile with a tendency to <strong>garden</strong> (notice how the image spans diagonally across quadrants). Your type of diagonal profile is known as a \"converter.\" You excel at transforming inner insights into productive action, bridging meaning with execution. Your diagonal nature allows you to move fluidly between reflection and creation. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Producer",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself taking action based solely on what works best for you, without considering the broader context or audience.\n\nTo break through, you need to identify the needs of your audience. Activate your <strong>Creative</strong> to understand what resonates with others. Then, you can activate your <strong>Synthesizer</strong> to integrate outside perspectives into your action plan.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your reflective side can get lost in an echo chamber of your own ideas. You're reflecting on what matters most to you…but without outside input, your perspective can become narrow.\n\nTo break through, you need to broaden your perspective. Activate your <strong>Synthesizer</strong> to explore diverse ideas and sources. Then, you can activate your <strong>Creative</strong> to express your enriched understanding in new ways."
    }
  },
  "PS-Architect": {
    "archetypeDescription": {
      "content": "<strong>Producer</strong> is your dominant sensemaking archetype, and <strong>Synthesizer</strong> is your secondary. This combination creates a builder's approach to sensemaking. You excel at systematic creation and structured progress, combining practical action with comprehensive understanding. Your strength lies in your ability to construct robust frameworks and methodologies, making complex projects manageable and sustainable."
    },
    "orientationDescription": {
      "content": "As a <strong>PS-Architect</strong>, you have a <strong>Northern</strong> profile with a tendency to <strong>architect</strong> (notice how the image is predominantly focused on the northern side). Northern profiles are known as \"builders.\" They excel at structured creation and systematic progress, combining productive action with synthesized understanding. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Producer",
      "content": "<strong>Your dominant sticking point:</strong> Your desire for action and progress can devolve into exhaustive tracking of every step. You're measuring everything with stopwatch precision, when sometimes you just need to build.\n\nTo break through, you need to step back and slow down. Activate your <strong>Creative</strong> to inject fresh innovation into your process. Then, you can activate your <strong>Inner Guide</strong> to reconnect with what truly matters.\n\n---\n\n<strong>Your secondary sticking point:</strong> You can get absorbed in researching and synthesizing information to the point of over-engineering. You're building Eiffel tower frameworks when all you needed was a simple beachfront hut.\n\nTo break through, you need to reconnect with what matters most. Activate your <strong>Inner Guide</strong> to clarify your purpose. Then, you can activate your <strong>Creative</strong> to find simpler, more elegant solutions."
    }
  },
  "PS-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Producer</strong> is your dominant sensemaking archetype, and <strong>Synthesizer</strong> is your secondary. This combination creates a builder's approach to sensemaking. You excel at systematic creation and structured progress, combining practical action with comprehensive understanding. Your strength lies in your ability to construct robust frameworks and methodologies, making complex projects manageable and sustainable."
    },
    "orientationDescription": {
      "content": "As a <strong>PS-Gardener</strong>, you have a <strong>Northern</strong> profile with a tendency to <strong>garden</strong> (notice how the image is predominantly focused on the northern side). Northern profiles are known as \"builders.\" They excel at structured creation and systematic progress, combining productive action with synthesized understanding. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Producer",
      "content": "<strong>Your dominant sticking point:</strong> Your desire for action and progress can devolve into exhaustive tracking of every step. You're measuring everything with stopwatch precision, when sometimes you just need to build.\n\nTo break through, you need to step back and slow down. Activate your <strong>Creative</strong> to inject fresh innovation into your process. Then, you can activate your <strong>Inner Guide</strong> to reconnect with what truly matters.\n\n---\n\n<strong>Your secondary sticking point:</strong> You can get absorbed in researching and synthesizing information to the point of over-engineering. You're building Eiffel tower frameworks when all you needed was a simple beachfront hut.\n\nTo break through, you need to reconnect with what matters most. Activate your <strong>Inner Guide</strong> to clarify your purpose. Then, you can activate your <strong>Creative</strong> to find simpler, more elegant solutions."
    }
  },
  "PC-Architect": {
    "archetypeDescription": {
      "content": "<strong>Producer</strong> is your dominant sensemaking archetype, and <strong>Creative</strong> is your secondary. This combination creates a maker's approach to sensemaking. You thrive on creative expression and productive output, naturally translating ideas into tangible results. Your strength lies in your ability to innovate and execute, though you may sometimes need to balance your action-oriented nature with deeper reflection."
    },
    "orientationDescription": {
      "content": "As a <strong>PC-Architect</strong>, you have an <strong>Eastern</strong> profile with a tendency to <strong>architect</strong> (notice how the image is predominantly focused on the eastern side). Eastern profiles are known as \"makers.\" Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Producer",
      "content": "<strong>Your dominant sticking point:</strong> You spend so much time 'doing' that you lose track of why you're doing it. The endless cycle of tasks and output can disconnect you from your deeper purpose.\n\nTo break through, you need to return to your vision. Activate your <strong>Inner Guide</strong> to reconnect with what truly matters. Then, you can activate your <strong>Synthesizer</strong> to understand how your actions align with your purpose.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your creative side can leave you feeling disorganized and overwhelmed by so many ideas and projects that nothing is getting finished.\n\nTo break through, you need to see the big picture. Activate your <strong>Synthesizer</strong> to organize your ideas into coherent patterns. Then, you can activate your <strong>Inner Guide</strong> to prioritize what matters most."
    }
  },
  "PC-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Producer</strong> is your dominant sensemaking archetype, and <strong>Creative</strong> is your secondary. This combination creates a maker's approach to sensemaking. You thrive on creative expression and productive output, naturally translating ideas into tangible results. Your strength lies in your ability to innovate and execute, though you may sometimes need to balance your action-oriented nature with deeper reflection."
    },
    "orientationDescription": {
      "content": "As a <strong>PC-Gardener</strong>, you have an <strong>Eastern</strong> profile with a tendency to <strong>garden</strong> (notice how the image is predominantly focused on the eastern side). Eastern profiles are known as \"makers.\" Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Producer",
      "content": "<strong>Your dominant sticking point:</strong> You spend so much time 'doing' that you lose track of why you're doing it. The endless cycle of tasks and output can disconnect you from your deeper purpose.\n\nTo break through, you need to return to your vision. Activate your <strong>Inner Guide</strong> to reconnect with what truly matters. Then, you can activate your <strong>Synthesizer</strong> to understand how your actions align with your purpose.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your creative side can leave you feeling disorganized and overwhelmed by so many ideas and projects that nothing is getting finished.\n\nTo break through, you need to see the big picture. Activate your <strong>Synthesizer</strong> to organize your ideas into coherent patterns. Then, you can activate your <strong>Inner Guide</strong> to prioritize what matters most."
    }
  },
  "SI-Architect": {
    "archetypeDescription": {
      "content": "<strong>Synthesizer</strong> is your dominant sensemaking archetype, and <strong>Inner Guide</strong> is your secondary. This combination creates a philosophical approach to sensemaking. You naturally seek deep understanding and meaning, often spending significant time in reflection and analysis. Your strength lies in your ability to synthesize complex ideas and find underlying patterns, though you may sometimes struggle with moving from contemplation to action."
    },
    "orientationDescription": {
      "content": "As a <strong>SI-Architect</strong>, you have a <strong>Western</strong> profile with a tendency to <strong>architect</strong> (notice how the image is predominantly focused on the western side). Western profiles are known as \"philosophers.\" Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Synthesizer",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself getting lost in understanding. You're researching, or connecting ideas, or following threads…but then the threads multiply, and you're caught following 'just one more' source.\n\nTo break through, you need to do something with your knowledge. Activate your <strong>Creative</strong> to express what you've learned. Then, you can activate your <strong>Producer</strong> to create with purpose.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your reflective mind can get lost in analysis. You're trying to understand your place, your purpose, your path…but then come the doubts, and you're caught in paralysis by analysis.\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to set a goal or deadline and take some action. Then, you can activate your <strong>Creative</strong> to find innovative ways to manifest your understanding.\n---\n\n<strong>As a Synthesizer, moving to the Inner Guide:</strong>\n\nWhen you combine your Synthesizer and Inner Guide archetypes with an Architect tendency, it's most difficult to access your Creative archetype—yet that's exactly what you most need. Since your tendency is to architect, the easiest way to move from understanding to expression is by tapping into your Producer archetype, which aligns with your structured approach to building.\n\n<strong>How can you structure your insights for systematic creative expression? What frameworks would help you manifest your understanding in innovative ways?</strong>\n\nOnce your Producer is activated, you will likely find it becomes easier to move into your Creative archetype, allowing you to express your deep understanding through original contributions."
    }
  },
  "SI-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Synthesizer</strong> is your dominant sensemaking archetype, and <strong>Inner Guide</strong> is your secondary. This combination creates a philosophical approach to sensemaking. You naturally seek deep understanding and meaning, often spending significant time in reflection and analysis. Your strength lies in your ability to synthesize complex ideas and find underlying patterns, though you may sometimes struggle with moving from contemplation to action."
    },
    "orientationDescription": {
      "content": "As a <strong>SI-Gardener</strong>, you have a <strong>Western</strong> profile with a tendency to <strong>garden</strong> (notice how the image is predominantly focused on the western side). Western profiles are known as \"philosophers.\" Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Synthesizer",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself getting lost in understanding. You're researching, or connecting ideas, or following threads…but then the threads multiply, and you're caught following 'just one more' source.\n\nTo break through, you need to do something with your knowledge. Activate your <strong>Creative</strong> to express what you've learned. Then, you can activate your <strong>Producer</strong> to create with purpose.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your reflective mind can get lost in analysis. You're trying to understand your place, your purpose, your path…but then come the doubts, and you're caught in paralysis by analysis.\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to set a goal or deadline and take some action. Then, you can activate your <strong>Creative</strong> to find innovative ways to manifest your understanding."
    }
  },
  "SP-Architect": {
    "archetypeDescription": {
      "content": "<strong>Synthesizer</strong> is your dominant sensemaking archetype, and <strong>Producer</strong> is your secondary. This combination creates a builder's approach to sensemaking. You excel at systematic creation and structured progress, combining practical action with comprehensive understanding. Your strength lies in your ability to construct robust frameworks and methodologies, making complex projects manageable and sustainable."
    },
    "orientationDescription": {
      "content": "As a <strong>SP-Architect</strong>, you have a <strong>Northern</strong> profile with a tendency to <strong>architect</strong> (notice how the image is predominantly focused on the northern side). Northern profiles are known as \"builders.\" They excel at structured creation and systematic progress, combining productive action with synthesized understanding. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Synthesizer",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself absorbed in researching and synthesizing information to the point of over-engineering. You're building Eiffel tower frameworks when all you needed was a simple beachfront hut.\n\nTo break through, you need to reconnect with what matters most. Activate your <strong>Inner Guide</strong> to clarify your purpose. Then, you can activate your <strong>Creative</strong> to find simpler, more elegant solutions.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your action-oriented side's desire for progress can devolve into exhaustive tracking of every step. You're measuring everything with stopwatch precision, when sometimes you just need to build.\n\nTo break through, you need to step back and slow down. Activate your <strong>Creative</strong> to inject fresh innovation into your process. Then, you can activate your <strong>Inner Guide</strong> to reconnect with what truly matters."
    }
  },
  "SP-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Synthesizer</strong> is your dominant sensemaking archetype, and <strong>Producer</strong> is your secondary. This combination creates a builder's approach to sensemaking. You excel at systematic creation and structured progress, combining practical action with comprehensive understanding. Your strength lies in your ability to construct robust frameworks and methodologies, making complex projects manageable and sustainable."
    },
    "orientationDescription": {
      "content": "As a <strong>SP-Gardener</strong>, you have a <strong>Northern</strong> profile with a tendency to <strong>garden</strong> (notice how the image is predominantly focused on the northern side). Northern profiles are known as \"builders.\" They excel at structured creation and systematic progress, combining productive action with synthesized understanding. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Synthesizer",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself absorbed in researching and synthesizing information to the point of over-engineering. You're building Eiffel tower frameworks when all you needed was a simple beachfront hut.\n\nTo break through, you need to reconnect with what matters most. Activate your <strong>Inner Guide</strong> to clarify your purpose. Then, you can activate your <strong>Creative</strong> to find simpler, more elegant solutions.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your action-oriented side's desire for progress can devolve into exhaustive tracking of every step. You're measuring everything with stopwatch precision, when sometimes you just need to build.\n\nTo break through, you need to step back and slow down. Activate your <strong>Creative</strong> to inject fresh innovation into your process. Then, you can activate your <strong>Inner Guide</strong> to reconnect with what truly matters."
    }
  },
  "SC-Architect": {
    "archetypeDescription": {
      "content": "<strong>Synthesizer</strong> is your dominant sensemaking archetype, and <strong>Creative</strong> is your secondary. This combination creates a translator's approach to sensemaking. You excel at bridging different worlds of understanding, making complex or abstract concepts accessible to others. Your strength lies in your ability to synthesize diverse perspectives and communicate insights across different contexts and audiences."
    },
    "orientationDescription": {
      "content": "As a <strong>SC-Architect</strong>, you have a <strong>Diagonal</strong> profile with a tendency to <strong>architect</strong> (notice how the image spans diagonally across quadrants). Your type of diagonal profile is known as a \"translator.\" You bridge creative expression with systematic synthesis, helping others understand complex ideas. Your diagonal nature gives you unique perspective-shifting abilities. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Synthesizer",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself getting lost in complexity. You're viewing every concept from all possible interdisciplinary perspectives, building elaborate conceptual frameworks that may obscure rather than clarify.\n\nTo break through, you need to ground yourself with clear intention. Activate your <strong>Inner Guide</strong> to reconnect with what truly matters. Then, you can activate your <strong>Producer</strong> to translate your understanding into concrete action.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your creative side can feel the internal tension of wanting your creation to be mind blowingly original and brilliant, leading to perfectionism and hesitation.\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to ship your work and iterate. Then, you can activate your <strong>Inner Guide</strong> to reflect on what you've learned from creating."
    }
  },
  "SC-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Synthesizer</strong> is your dominant sensemaking archetype, and <strong>Creative</strong> is your secondary. This combination creates a translator's approach to sensemaking. You excel at bridging different worlds of understanding, making complex or abstract concepts accessible to others. Your strength lies in your ability to synthesize diverse perspectives and communicate insights across different contexts and audiences."
    },
    "orientationDescription": {
      "content": "As a <strong>SC-Gardener</strong>, you have a <strong>Diagonal</strong> profile with a tendency to <strong>garden</strong> (notice how the image spans diagonally across quadrants). Your type of diagonal profile is known as a \"translator.\" You bridge creative expression with systematic synthesis, helping others understand complex ideas. Your diagonal nature gives you unique perspective-shifting abilities. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Synthesizer",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself getting lost in complexity. You're viewing every concept from all possible interdisciplinary perspectives, building elaborate conceptual frameworks that may obscure rather than clarify.\n\nTo break through, you need to ground yourself with clear intention. Activate your <strong>Inner Guide</strong> to reconnect with what truly matters. Then, you can activate your <strong>Producer</strong> to translate your understanding into concrete action.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your creative side can feel the internal tension of wanting your creation to be mind blowingly original and brilliant, leading to perfectionism and hesitation.\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to ship your work and iterate. Then, you can activate your <strong>Inner Guide</strong> to reflect on what you've learned from creating."
    }
  },
  "CI-Architect": {
    "archetypeDescription": {
      "content": "<strong>Creative</strong> is your dominant sensemaking archetype, and <strong>Inner Guide</strong> is your secondary. This combination creates an explorer's approach to sensemaking. You thrive on creative discovery and meaningful investigation, naturally seeking novel perspectives and innovative solutions. Your strength lies in your ability to venture into uncharted territory and find unique insights that others might miss."
    },
    "orientationDescription": {
      "content": "As a <strong>CI-Architect</strong>, you have a <strong>Southern</strong> profile with a tendency to <strong>architect</strong> (notice how the image is predominantly focused on the southern side). Southern profiles are known as \"explorers.\" They thrive on creative introspection and meaningful discovery, combining inner guidance with creative expression. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Creative",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself lost in perfecting your vision. You're creating, iterating, refining…but as they say: 'Real artists ship.'\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to set deadlines and ship your work. Then, you can activate your <strong>Synthesizer</strong> to make sense of what you've created.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your reflective mind generates so many ideas, interests and insights that you feel scattered across too many different projects and pursuits.\n\nTo break through, you need to organize your insights. Activate your <strong>Synthesizer</strong> to connect your ideas into coherent patterns. Then, you can activate your <strong>Producer</strong> to systematically manifest your organized vision."
    }
  },
  "CI-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Creative</strong> is your dominant sensemaking archetype, and <strong>Inner Guide</strong> is your secondary. This combination creates an explorer's approach to sensemaking. You thrive on creative discovery and meaningful investigation, naturally seeking novel perspectives and innovative solutions. Your strength lies in your ability to venture into uncharted territory and find unique insights that others might miss."
    },
    "orientationDescription": {
      "content": "As a <strong>CI-Gardener</strong>, you have a <strong>Southern</strong> profile with a tendency to <strong>garden</strong> (notice how the image is predominantly focused on the southern side). Southern profiles are known as \"explorers.\" They thrive on creative introspection and meaningful discovery, combining inner guidance with creative expression. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Creative",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself lost in perfecting your vision. You're creating, iterating, refining…but as they say: 'Real artists ship.'\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to set deadlines and ship your work. Then, you can activate your <strong>Synthesizer</strong> to make sense of what you've created.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your reflective mind generates so many ideas, interests and insights that you feel scattered across too many different projects and pursuits.\n\nTo break through, you need to organize your insights. Activate your <strong>Synthesizer</strong> to connect your ideas into coherent patterns. Then, you can activate your <strong>Producer</strong> to systematically manifest your organized vision."
    }
  },
  "CP-Architect": {
    "archetypeDescription": {
      "content": "<strong>Creative</strong> is your dominant sensemaking archetype, and <strong>Producer</strong> is your secondary. This combination creates a maker's approach to sensemaking. You thrive on creative expression and productive output, naturally translating ideas into tangible results. Your strength lies in your ability to innovate and execute, though you may sometimes need to balance your action-oriented nature with deeper reflection."
    },
    "orientationDescription": {
      "content": "As a <strong>CP-Architect</strong>, you have an <strong>Eastern</strong> profile with a tendency to <strong>architect</strong> (notice how the image is predominantly focused on the eastern side). Eastern profiles are known as \"makers.\" Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Creative",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself feeling disorganized and overwhelmed by so many ideas and projects that nothing is getting finished.\n\nTo break through, you need to see the big picture. Activate your <strong>Synthesizer</strong> to organize your ideas into coherent patterns. Then, you can activate your <strong>Inner Guide</strong> to prioritize what matters most.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your productive side can lead you to spend so much time 'doing' that you lose track of why you're doing it. The endless cycle of tasks and output can disconnect you from your deeper purpose.\n\nTo break through, you need to return to your vision. Activate your <strong>Inner Guide</strong> to reconnect with what truly matters. Then, you can activate your <strong>Synthesizer</strong> to understand how your actions align with your purpose."
    }
  },
  "CP-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Creative</strong> is your dominant sensemaking archetype, and <strong>Producer</strong> is your secondary. This combination creates a maker's approach to sensemaking. You thrive on creative expression and productive output, naturally translating ideas into tangible results. Your strength lies in your ability to innovate and execute, though you may sometimes need to balance your action-oriented nature with deeper reflection."
    },
    "orientationDescription": {
      "content": "As a <strong>CP-Gardener</strong>, you have an <strong>Eastern</strong> profile with a tendency to <strong>garden</strong> (notice how the image is predominantly focused on the eastern side). Eastern profiles are known as \"makers.\" Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Creative",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself feeling disorganized and overwhelmed by so many ideas and projects that nothing is getting finished.\n\nTo break through, you need to see the big picture. Activate your <strong>Synthesizer</strong> to organize your ideas into coherent patterns. Then, you can activate your <strong>Inner Guide</strong> to prioritize what matters most.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your productive side can lead you to spend so much time 'doing' that you lose track of why you're doing it. The endless cycle of tasks and output can disconnect you from your deeper purpose.\n\nTo break through, you need to return to your vision. Activate your <strong>Inner Guide</strong> to reconnect with what truly matters. Then, you can activate your <strong>Synthesizer</strong> to understand how your actions align with your purpose."
    }
  },
  "CS-Architect": {
    "archetypeDescription": {
      "content": "<strong>Creative</strong> is your dominant sensemaking archetype, and <strong>Synthesizer</strong> is your secondary. This combination creates a translator's approach to sensemaking. You excel at bridging different worlds of understanding, making complex or abstract concepts accessible to others. Your strength lies in your ability to synthesize diverse perspectives and communicate insights across different contexts and audiences."
    },
    "orientationDescription": {
      "content": "As a <strong>CS-Architect</strong>, you have a <strong>Diagonal</strong> profile with a tendency to <strong>architect</strong> (notice how the image spans diagonally across quadrants). Your type of diagonal profile is known as a \"translator.\" You bridge creative expression with systematic synthesis, helping others understand complex ideas. Your diagonal nature gives you unique perspective-shifting abilities. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Architect</strong> is your dominant sensemaking tendency. This means you gravitate towards structuring and organizing the things around you. However, it doesn't mean the things around you are organized, only that you prefer clarity and understanding over uncertainty, but sometimes even…opportunities."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Creative",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself feeling the internal tension of wanting your creation to be mind blowingly original and brilliant, leading to perfectionism and hesitation.\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to ship your work and iterate. Then, you can activate your <strong>Inner Guide</strong> to reflect on what you've learned from creating.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your synthesizing side can get lost in complexity. You're viewing every concept from all possible interdisciplinary perspectives, building elaborate conceptual frameworks that may obscure rather than clarify.\n\nTo break through, you need to ground yourself with clear intention. Activate your <strong>Inner Guide</strong> to reconnect with what truly matters. Then, you can activate your <strong>Producer</strong> to translate your understanding into concrete action."
    }
  },
  "CS-Gardener": {
    "archetypeDescription": {
      "content": "<strong>Creative</strong> is your dominant sensemaking archetype, and <strong>Synthesizer</strong> is your secondary. This combination creates a translator's approach to sensemaking. You excel at bridging different worlds of understanding, making complex or abstract concepts accessible to others. Your strength lies in your ability to synthesize diverse perspectives and communicate insights across different contexts and audiences."
    },
    "orientationDescription": {
      "content": "As a <strong>CS-Gardener</strong>, you have a <strong>Diagonal</strong> profile with a tendency to <strong>garden</strong> (notice how the image spans diagonally across quadrants). Your type of diagonal profile is known as a \"translator.\" You bridge creative expression with systematic synthesis, helping others understand complex ideas. Your diagonal nature gives you unique perspective-shifting abilities. Please note that to make the most of your mind, you must be able to move between all archetypes."
    },
    "tendencyDescription": {
      "content": "The <strong>Gardener</strong> is your dominant sensemaking tendency. This means you prefer flexibility and emergent approaches, allowing ideas and projects to develop organically. You thrive in ambiguous situations and are comfortable navigating uncertainty, often discovering unexpected opportunities through exploration."
    },
    "stuckUnstuck": {
      "title": "Sticking Points & Breaking Through for the Creative",
      "content": "<strong>Your dominant sticking point:</strong> You find yourself feeling the internal tension of wanting your creation to be mind blowingly original and brilliant, leading to perfectionism and hesitation.\n\nTo break through, you need to act. Activate your <strong>Producer</strong> to ship your work and iterate. Then, you can activate your <strong>Inner Guide</strong> to reflect on what you've learned from creating.\n\n---\n\n<strong>Your secondary sticking point:</strong> Your synthesizing side can get lost in complexity. You're viewing every concept from all possible interdisciplinary perspectives, building elaborate conceptual frameworks that may obscure rather than clarify.\n\nTo break through, you need to ground yourself with clear intention. Activate your <strong>Inner Guide</strong> to reconnect with what truly matters. Then, you can activate your <strong>Producer</strong> to translate your understanding into concrete action."
    }
  }
};

console.log('✅ Profile data loaded:', Object.keys(window.STTI_PROFILES).length, 'profiles');
